import AppKit
import Observation

/// One clipboard text that a reader has not saved yet.
public struct ClipboardEntry: Identifiable, Equatable {

    // MARK: - Properties

    public let id = UUID()
    public let text: String

    // MARK: - Initialization

    public init(text: String) { self.text = text }
}

/// Recent clipboard text, held until the reader saves it or it falls out of the list.
///
/// Nothing here reaches the database on its own. A reader saves an entry, and
/// then the entry disappears because the store holds the same text.
@MainActor @Observable
public final class ClipboardInbox {

    // MARK: - Properties

    public static let copiedNoteType = NSPasteboard.PasteboardType("com.piper.saved-notes")
    private static let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        copiedNoteType,
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]
    private let store: CaptureStore
    private let pasteboard: NSPasteboard
    private var items: [ClipboardEntry] = []
    @ObservationIgnored private var changeCount: Int?
    @ObservationIgnored private var timer: Timer?

    public var entries: [ClipboardEntry] {
        items.filter { item in !store.notes.contains { $0.text == item.text } }
    }

    // MARK: - Initialization

    public init(store: CaptureStore, pasteboard: NSPasteboard = .general) {
        self.store = store
        self.pasteboard = pasteboard
    }

    // MARK: - Polling

    public func start() {
        guard timer == nil else { return }
        poll()
        let timer = Timer(timeInterval: 0.6, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in self?.poll() }
        }
        timer.tolerance = 0.1
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    public func stop() { timer?.invalidate(); timer = nil }

    public func poll() {
        let version = pasteboard.changeCount
        guard version != changeCount else { return }
        changeCount = version
        guard Self.ignoredTypes.isDisjoint(with: pasteboard.types ?? []) else { return }
        let texts = (pasteboard.pasteboardItems ?? []).compactMap { item -> String? in
            guard Self.ignoredTypes.isDisjoint(with: item.types) else { return nil }
            return item.string(forType: .string)
        }
        guard pasteboard.changeCount == version else { changeCount = nil; return }
        receive(texts)
    }

    public func receive(_ texts: [String]) {
        var updated = items
        for text in texts.reversed() {
            guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
                  text.utf8.count <= 500_000,
                  !store.notes.contains(where: { $0.text == text }) else { continue }
            let existing = updated.first { $0.text == text }
            updated.removeAll { $0.text == text }
            updated.insert(existing ?? ClipboardEntry(text: text), at: 0)
        }
        updated = Array(updated.prefix(10))
        if updated != items { items = updated }
    }

    // MARK: - Saving

    @discardableResult public func save(_ id: UUID) -> Bool {
        guard let entry = entries.first(where: { $0.id == id }),
              store.add(entry.text, source: "Clipboard", to: store.activeSection, interpretSection: false) else { return false }
        return true
    }
}
