import AppKit
import Observation

/// One clipboard text that a reader has not saved yet.
public struct ClipboardEntry: Identifiable, Equatable {

    // MARK: - Properties

    public let id: UUID
    public let text: String
    /// The last time the reader copied this text.
    public let copiedAt: Date
    /// The name of the application that was in front when the text arrived.
    public let source: String?

    // MARK: - Initialization

    public init(id: UUID = UUID(), text: String, copiedAt: Date = Date(), source: String? = nil) {
        self.id = id
        self.text = text
        self.copiedAt = copiedAt
        self.source = source
    }
}

/// Recent clipboard text, held until the reader saves it or it falls out of the list.
///
/// Nothing here reaches the database on its own. A reader saves an entry, and
/// then the entry disappears because the store holds the same text.
@MainActor @Observable
public final class ClipboardInbox {

    // MARK: - Properties

    public static let copiedNoteType = NSPasteboard.PasteboardType("com.piper.saved-notes")
    /// The number of texts the history keeps. The history lives in memory only.
    public static let historyLimit = 50
    private static let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        copiedNoteType,
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]
    private let store: CaptureStore
    private let pasteboard: NSPasteboard
    private var items: [ClipboardEntry] = []
    @ObservationIgnored private var changeCount: Int?
    @ObservationIgnored private var timer: Timer?

    public var entries: [ClipboardEntry] {
        items.filter { item in !store.notes.contains { $0.text == item.text } }
    }

    // MARK: - Initialization

    public init(store: CaptureStore, pasteboard: NSPasteboard = .general) {
        self.store = store
        self.pasteboard = pasteboard
    }

    // MARK: - Polling

    public func start() {
        guard timer == nil else { return }
        poll()
        let timer = Timer(timeInterval: 0.6, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in self?.poll() }
        }
        timer.tolerance = 0.1
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    public func stop() { timer?.invalidate(); timer = nil }

    public func poll() {
        let version = pasteboard.changeCount
        guard version != changeCount else { return }
        changeCount = version
        guard Self.ignoredTypes.isDisjoint(with: pasteboard.types ?? []) else { return }
        let texts = (pasteboard.pasteboardItems ?? []).compactMap { item -> String? in
            guard Self.ignoredTypes.isDisjoint(with: item.types) else { return nil }
            return item.string(forType: .string)
        }
        guard pasteboard.changeCount == version else { changeCount = nil; return }
        receive(texts, source: NSWorkspace.shared.frontmostApplication?.localizedName)
    }

    /// Adds copied texts to the front of the history.
    ///
    /// A text that the history already holds moves to the front and keeps its
    /// identity, so a selection of that entry survives the copy.
    public func receive(_ texts: [String], source: String? = nil, at date: Date = Date()) {
        var updated = items
        for text in texts.reversed() {
            guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
                  text.utf8.count <= 500_000,
                  !store.notes.contains(where: { $0.text == text }) else { continue }
            let existing = updated.first { $0.text == text }
            updated.removeAll { $0.text == text }
            updated.insert(ClipboardEntry(id: existing?.id ?? UUID(), text: text, copiedAt: date, source: source), at: 0)
        }
        updated = Array(updated.prefix(Self.historyLimit))
        if updated != items { items = updated }
    }

    /// Forgets every text that the reader has not saved.
    public func clear() {
        items.removeAll()
    }

    // MARK: - Saving

    @discardableResult public func save(_ id: UUID) -> Bool {
        guard let entry = entries.first(where: { $0.id == id }),
              store.add(entry.text, source: "Clipboard", to: "Inbox", interpretSection: false) else { return false }
        return true
    }
}
