import AppKit
import CapturesDatabase
import Observation

/// One clipboard text that a reader has not saved yet.
public struct ClipboardEntry: Identifiable, Equatable {

    // MARK: - Properties

    public let id: UUID
    public let text: String
    /// The last time the reader copied this text.
    public let copiedAt: Date
    /// The name of the application that was in front when the text arrived.
    public let source: String?

    // MARK: - Initialization

    public init(id: UUID = UUID(), text: String, copiedAt: Date = Date(), source: String? = nil) {
        self.id = id
        self.text = text
        self.copiedAt = copiedAt
        self.source = source
    }
}

/// Recent clipboard text, held until the reader saves it or it falls out of the list.
///
/// The history goes into the clipboard table of the note database, so it
/// survives a restart. It never becomes a note on its own. A reader saves an
/// entry, and then the entry disappears because the store holds the same text.
@MainActor @Observable
public final class ClipboardInbox {

    // MARK: - Properties

    public static let copiedNoteType = NSPasteboard.PasteboardType("com.piper.saved-notes")
    /// The number of texts the history keeps.
    public static let historyLimit = 50
    /// The age after which a text leaves the history.
    nonisolated public static let defaultRetention: TimeInterval = 7 * 24 * 60 * 60
    private static let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        copiedNoteType,
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]
    private let store: CaptureStore
    private let pasteboard: NSPasteboard
    private let retention: TimeInterval
    private var items: [ClipboardEntry] = []
    @ObservationIgnored private var changeCount: Int?
    @ObservationIgnored private var timer: Timer?

    public var entries: [ClipboardEntry] {
        items.filter { item in !store.notes.contains { $0.text == item.text } }
    }

    // MARK: - Initialization

    public init(store: CaptureStore, pasteboard: NSPasteboard = .general, retention: TimeInterval = defaultRetention, now: Date = Date()) {
        self.store = store
        self.pasteboard = pasteboard
        self.retention = retention
        guard let database = store.database else { return }
        do {
            try database.removeClipboard(before: now.addingTimeInterval(-retention))
            let loaded = try database.loadClipboard().map {
                ClipboardEntry(id: $0.id, text: $0.text, copiedAt: $0.copiedAt, source: $0.source)
            }
            items = Array(loaded.prefix(Self.historyLimit))
            persist(items, previous: loaded)
        } catch { store.report(error) }
    }

    // MARK: - Polling

    public func start() {
        guard timer == nil else { return }
        poll()
        let timer = Timer(timeInterval: 0.6, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in self?.poll() }
        }
        timer.tolerance = 0.1
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    public func stop() { timer?.invalidate(); timer = nil }

    public func poll() {
        removeExpired()
        let version = pasteboard.changeCount
        guard version != changeCount else { return }
        changeCount = version
        guard Self.ignoredTypes.isDisjoint(with: pasteboard.types ?? []) else { return }
        let texts = (pasteboard.pasteboardItems ?? []).compactMap { item -> String? in
            guard Self.ignoredTypes.isDisjoint(with: item.types) else { return nil }
            return item.string(forType: .string)
        }
        guard pasteboard.changeCount == version else { changeCount = nil; return }
        receive(texts, source: NSWorkspace.shared.frontmostApplication?.localizedName)
    }

    /// Adds copied texts to the front of the history.
    ///
    /// A text that the history already holds moves to the front and keeps its
    /// identity, so a selection of that entry survives the copy.
    public func receive(_ texts: [String], source: String? = nil, at date: Date = Date()) {
        var updated = items
        for text in texts.reversed() {
            guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
                  text.utf8.count <= 500_000,
                  !store.notes.contains(where: { $0.text == text }) else { continue }
            let existing = updated.first { $0.text == text }
            updated.removeAll { $0.text == text }
            updated.insert(ClipboardEntry(id: existing?.id ?? UUID(), text: text, copiedAt: date, source: source), at: 0)
        }
        updated = Array(updated.prefix(Self.historyLimit).filter { !isExpired($0, at: date) })
        guard updated != items else { return }
        persist(updated, previous: items)
        items = updated
    }

    /// Removes the texts that are older than the retention period.
    public func removeExpired(at date: Date = Date()) {
        guard items.contains(where: { isExpired($0, at: date) }) else { return }
        let updated = items.filter { !isExpired($0, at: date) }
        persist(updated, previous: items)
        items = updated
    }

    /// Forgets every text that the reader has not saved.
    public func clear() {
        do { try store.database?.removeAllClipboard() } catch { store.report(error) }
        items.removeAll()
    }

    // MARK: - Saving

    @discardableResult public func save(_ id: UUID) -> Bool {
        guard let entry = entries.first(where: { $0.id == id }),
              store.add(entry.text, source: "Clipboard", to: "Inbox", interpretSection: false) else { return false }
        return true
    }

    // MARK: - Private

    private func isExpired(_ entry: ClipboardEntry, at date: Date) -> Bool {
        entry.copiedAt < date.addingTimeInterval(-retention)
    }

    /// Writes the entries that changed and removes the entries that left the history.
    ///
    /// A failed write keeps the history in memory and shows the error.
    private func persist(_ updated: [ClipboardEntry], previous: [ClipboardEntry]) {
        guard let database = store.database else { return }
        let changed = updated.filter { !previous.contains($0) }.map {
            ClipboardRecord(id: $0.id, text: $0.text, copiedAt: $0.copiedAt, source: $0.source)
        }
        let kept = Set(updated.map(\.id))
        let removed = previous.map(\.id).filter { !kept.contains($0) }
        do { try database.saveClipboard(changed, removing: removed) } catch { store.report(error) }
    }
}
