import AppKit
import Observation

struct ClipboardEntry: Identifiable, Equatable {
    let id = UUID()
    let text: String
}

@MainActor @Observable
final class ClipboardInbox {
    static let copiedNoteType = NSPasteboard.PasteboardType("com.piper.saved-notes")
    private static let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        copiedNoteType,
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]
    private let store: AppStore
    private let pasteboard: NSPasteboard
    private var items: [ClipboardEntry] = []
    @ObservationIgnored private var changeCount: Int?
    @ObservationIgnored private var timer: Timer?

    var entries: [ClipboardEntry] {
        items.filter { item in !store.notes.contains { $0.text == item.text } }
    }

    init(store: AppStore, pasteboard: NSPasteboard = .general) {
        self.store = store
        self.pasteboard = pasteboard
    }

    func start() {
        guard timer == nil else { return }
        poll()
        let timer = Timer(timeInterval: 0.6, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in self?.poll() }
        }
        timer.tolerance = 0.1
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() { timer?.invalidate(); timer = nil }

    func poll() {
        let version = pasteboard.changeCount
        guard version != changeCount else { return }
        changeCount = version
        guard Self.ignoredTypes.isDisjoint(with: pasteboard.types ?? []) else { return }
        let texts = (pasteboard.pasteboardItems ?? []).compactMap { item -> String? in
            guard Self.ignoredTypes.isDisjoint(with: item.types) else { return nil }
            return item.string(forType: .string)
        }
        guard pasteboard.changeCount == version else { changeCount = nil; return }
        receive(texts)
    }

    func receive(_ texts: [String]) {
        var updated = items
        for text in texts.reversed() {
            guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
                  text.utf8.count <= 500_000,
                  !store.notes.contains(where: { $0.text == text }) else { continue }
            let existing = updated.first { $0.text == text }
            updated.removeAll { $0.text == text }
            updated.insert(existing ?? ClipboardEntry(text: text), at: 0)
        }
        updated = Array(updated.prefix(10))
        if updated != items { items = updated }
    }

    @discardableResult func save(_ id: UUID) -> Bool {
        guard let entry = entries.first(where: { $0.id == id }),
              store.add(entry.text, source: "Clipboard", to: store.activeSection, interpretSection: false) else { return false }
        return true
    }
}
